-- Migración para crear la tabla de ejercicios y sembrar los movimientos de CrossFit

-- 1. Crear la tabla de ejercicios
CREATE TABLE IF NOT EXISTS ejercicios (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    categoria TEXT NOT NULL,
    descripcion TEXT,
    equipamiento TEXT NOT NULL,
    url_video TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS
ALTER TABLE ejercicios ENABLE ROW LEVEL SECURITY;

-- 3. Crear política permisiva para desarrollo rápido
CREATE POLICY "Permitir todo acceso público a ejercicios" ON ejercicios FOR ALL USING (true) WITH CHECK (true);

-- 4. Sembrado (seeder) de ejercicios clásicos de CrossFit
INSERT INTO ejercicios (nombre, categoria, descripcion, equipamiento) VALUES
('Air Squat', 'Gimnasia', 'Sentadilla libre con el peso corporal. Mantener talones apoyados, espalda recta y romper el paralelo.', 'Ninguno'),
('Push-up', 'Gimnasia', 'Flexiones de brazos rozando el pecho contra el suelo y extendiendo los codos por completo.', 'Ninguno'),
('Pull-up', 'Gimnasia', 'Dominadas en barra fija. Pasar la barbilla por encima de la barra utilizando kipping, mariposa o estricta.', 'Barra de dominadas'),
('Chest-to-Bar Pull-up', 'Gimnasia', 'Dominadas tocando el pecho con la barra debajo de las clavículas.', 'Barra de dominadas'),
('Bar Muscle-up', 'Gimnasia', 'Transición gimnástica para pasar desde suspensión a apoyo sobre la barra extendiendo los codos.', 'Barra de dominadas'),
('Ring Muscle-up', 'Gimnasia', 'Transición gimnástica en anillas desde suspensión a apoyo sobre las mismas extendiendo los codos.', 'Anillas de gimnasia'),
('Toes-to-Bar (T2B)', 'Gimnasia', 'Colgado de la barra, llevar ambos pies simultáneamente a tocar la barra entre las manos.', 'Barra de dominadas'),
('Knees-to-Elbows (K2E)', 'Gimnasia', 'Colgado de la barra, llevar las rodillas a tocar los codos.', 'Barra de dominadas'),
('Handstand Push-up (HSPU)', 'Gimnasia', 'Flexiones haciendo el pino apoyado contra la pared. Se permite kipping o estricto.', 'Pared / Abmat'),
('Handstand Walk', 'Gimnasia', 'Caminar sobre las manos con el cuerpo invertido manteniendo el core activo.', 'Ninguno'),
('Burpee', 'Gimnasia', 'Llevar el pecho al suelo, ponerse de pie y realizar un salto con aplauso sobre la cabeza.', 'Ninguno'),
('Pistol Squat', 'Gimnasia', 'Sentadilla profunda a una sola pierna manteniendo la otra extendida hacia el frente sin tocar el suelo.', 'Ninguno'),
('GHD Sit-up', 'Gimnasia', 'Abdominales en el banco de GHD, tocando el suelo detrás con las manos y luego regresando a tocar el rodillo.', 'Banco GHD'),
('Rope Climb', 'Gimnasia', 'Trepar por la cuerda hasta una marca determinada utilizando técnica de pies (J-cup o wrap).', 'Cuerda de trepa'),
('Double Under (DU)', 'Monoestructural', 'Salto doble de comba. La cuerda pasa dos veces por debajo de los pies en un solo salto.', 'Comba / Cuerda'),
('Row (Remo)', 'Monoestructural', 'Ejercicio cardiovascular en remo indoor medido en calorías o metros.', 'Remo Concept2'),
('Run (Carrera)', 'Monoestructural', 'Carrera a pie al aire libre o en cinta para desarrollo aeróbico.', 'Ninguno'),
('Box Jump', 'Monoestructural', 'Salto a un cajón de madera o espuma, extendiendo la cadera por completo arriba.', 'Cajón (Box)'),
('Box Jump Over', 'Monoestructural', 'Salto sobre el cajón sin necesidad de extender la cadera en el tope, descendiendo por el otro lado.', 'Cajón (Box)'),
('Wall Ball Shot', 'Monoestructural', 'Lanzamiento de balón medicinal a una diana a 9 o 10 pies tras hacer una sentadilla profunda.', 'Balón Medicinal'),
('Clean & Jerk', 'Halterofilia', 'Levantamiento de la barra en dos tiempos: desde el suelo a los hombros (clean) y luego sobre la cabeza (jerk).', 'Barra'),
('Power Clean', 'Halterofilia', 'Cargar la barra del suelo a los hombros recibiéndola en una posición de media sentadilla.', 'Barra'),
('Squat Clean', 'Halterofilia', 'Cargar la barra del suelo a los hombros recibiéndola en sentadilla profunda.', 'Barra'),
('Hang Clean', 'Halterofilia', 'Cargar la barra comenzando desde una posición colgante (sobre las rodillas) hasta los hombros.', 'Barra'),
('Snatch', 'Halterofilia', 'Arrancada. Levantamiento de la barra en un solo movimiento desde el suelo a por encima de la cabeza recibiendo abajo.', 'Barra'),
('Power Snatch', 'Halterofilia', 'Arrancada recibiendo la barra por encima de la cabeza en media sentadilla.', 'Barra'),
('Squat Snatch', 'Halterofilia', 'Arrancada recibiendo la barra en sentadilla profunda con extensión completa de brazos.', 'Barra'),
('Hang Snatch', 'Halterofilia', 'Arrancada comenzando desde una posición colgante (sobre las rodillas) directo a sobre la cabeza.', 'Barra'),
('Deadlift', 'Halterofilia', 'Peso muerto. Levantar la barra desde el suelo hasta la extensión completa de la cadera.', 'Barra'),
('Sumo Deadlift High Pull', 'Halterofilia', 'Peso muerto con postura ancha (sumo) y jalón alto llevando la barra hasta la barbilla.', 'Barra'),
('Thruster', 'Halterofilia', 'Combinación de una sentadilla frontal profunda seguida de un press de hombros en un solo movimiento continuo.', 'Barra'),
('Front Squat', 'Halterofilia', 'Sentadilla con la barra apoyada en la parte delantera de los hombros en posición de rack.', 'Barra'),
('Back Squat', 'Halterofilia', 'Sentadilla con la barra cargada en la parte trasera de los hombros.', 'Barra'),
('Overhead Squat', 'Halterofilia', 'Sentadilla manteniendo la barra completamente extendida sobre la cabeza con agarre ancho (snatch grip).', 'Barra'),
('Push Press', 'Halterofilia', 'Press de hombros utilizando un ligero impulso de piernas (dip & drive) sin volver a flexionar rodillas.', 'Barra'),
('Push Jerk', 'Halterofilia', 'Press de hombros impulsado con piernas y recibiendo con flexión de rodillas bajo la barra antes de extender.', 'Barra'),
('Kettlebell Swing (Americano)', 'Halterofilia', 'Balanceo de kettlebell terminando con la pesa completamente vertical sobre la cabeza.', 'Pesa Rusa (Kettlebell)'),
('Dumbbell Snatch', 'Halterofilia', 'Arrancada con mancuerna a una sola mano desde el suelo hasta arriba de la cabeza en un solo movimiento.', 'Mancuerna (Dumbbell)'),
('Devils Press', 'Halterofilia', 'Combinación de un burpee sobre las mancuernas seguido de un swing/snatch con ambas mancuernas sobre la cabeza.', 'Mancuernas'),
('Turkish Get-up', 'Halterofilia', 'Levantamiento turco. Pasar de acostado a estar de pie sosteniendo una mancuerna o kettlebell extendida arriba.', 'Pesa Rusa o Mancuerna'),
('Medicine Ball Clean', 'Halterofilia', 'Cargar el balón medicinal desde el suelo recibiéndolo en una sentadilla profunda.', 'Balón Medicinal'),
('Jumping Squat', 'Gimnasia', 'Sentadilla libre seguida de una extensión explosiva de cadera y rodillas para despegar los pies del suelo.', 'Ninguno'),
('Dumbbell Power Clean', 'Halterofilia', 'Cargar las mancuernas desde el suelo hasta los hombros recibiéndolas en posición de media sentadilla.', 'Mancuernas'),
('Dumbbell Squat Clean', 'Halterofilia', 'Cargar las mancuernas desde el suelo hasta los hombros recibiéndolas en una sentadilla profunda.', 'Mancuernas'),
('Double Dumbbell Snatch', 'Halterofilia', 'Arrancada con dos mancuernas de manera simultánea desde el suelo hasta por encima de la cabeza.', 'Mancuernas'),
('Dumbbell Thruster', 'Halterofilia', 'Sentadilla frontal profunda con mancuernas seguida de un empuje sobre la cabeza en un movimiento fluido.', 'Mancuernas'),
('Single-arm Dumbbell Thruster', 'Halterofilia', 'Sentadilla profunda sosteniendo una sola mancuerna en posición de rack, seguida de un press sobre la cabeza.', 'Mancuerna (Dumbbell)'),
('Kettlebell Thruster', 'Halterofilia', 'Sentadilla profunda sosteniendo una pesa rusa en rack, seguido de press sobre la cabeza.', 'Pesa Rusa (Kettlebell)'),
('Kettlebell Snatch', 'Halterofilia', 'Arrancada con pesa rusa desde una posición de balanceo (swing) directo a sobre la cabeza a un brazo.', 'Pesa Rusa (Kettlebell)'),
('Kettlebell Clean', 'Halterofilia', 'Cargar la pesa rusa desde el balanceo (swing) hasta la posición de rack en los hombros.', 'Pesa Rusa (Kettlebell)'),
('Dumbbell Deadlift', 'Halterofilia', 'Peso muerto con dos mancuernas, tocando un extremo de cada mancuerna en el suelo a los costados del cuerpo.', 'Mancuernas'),
('Kettlebell Deadlift', 'Halterofilia', 'Peso muerto levantando una o dos pesas rusas desde el suelo manteniendo la espalda neutra.', 'Pesa Rusa (Kettlebell)'),
('Dumbbell Front Squat', 'Halterofilia', 'Sentadilla frontal sosteniendo un par de mancuernas sobre los hombros.', 'Mancuernas'),
('Goblet Squat', 'Halterofilia', 'Sentadilla profunda sosteniendo una mancuerna o pesa rusa pegada al pecho.', 'Pesa Rusa o Mancuerna'),
('Kettlebell Swing (Ruso)', 'Halterofilia', 'Balanceo de pesa rusa llevando el peso hasta la altura de los ojos.', 'Pesa Rusa (Kettlebell)'),
('Dumbbell Walking Lunge', 'Halterofilia', 'Zancadas caminando sosteniendo mancuernas a los costados del cuerpo o sobre los hombros.', 'Mancuernas'),
('Burpee Box Jump Over', 'Monoestructural', 'Realizar un burpee en el suelo y luego saltar por encima del cajón hacia el otro lado.', 'Cajón (Box)'),
('Burpee Pull-up', 'Gimnasia', 'Realizar un burpee y, al ponerse de pie de un salto, colgarse de la barra y realizar una dominada.', 'Barra de dominadas'),
('Strict Pull-up', 'Gimnasia', 'Dominadas estrictas en barra sin ayuda de impulso ni balanceo de piernas (kipping).', 'Barra de dominadas'),
('Strict Chest-to-Bar Pull-up', 'Gimnasia', 'Dominadas estrictas llevando el pecho a tocar la barra fija por debajo de las clavículas.', 'Barra de dominadas'),
('Strict Handstand Push-up', 'Gimnasia', 'Flexiones haciendo el pino de forma estrictamente de fuerza, sin balanceo de cadera (kipping).', 'Pared / Abmat'),
('Deficit Handstand Push-up', 'Gimnasia', 'Flexiones de pino con las manos elevadas sobre discos o bloques para aumentar el rango de movimiento.', 'Pared / Discos'),
('Wall Walk', 'Gimnasia', 'Caminar hacia atrás en la pared con las manos y los pies desde el suelo hasta quedar en vertical de pino de cara a la pared.', 'Pared'),
('Cossack Squat', 'Gimnasia', 'Sentadilla lateral profunda a una sola pierna desplazando el peso hacia un lado mientras la otra pierna permanece extendida.', 'Ninguno'),
('Bulgarian Split Squat', 'Halterofilia', 'Zancada estática con un pie elevado por detrás sobre un banco o cajón.', 'Banco / Cajón'),
('Dumbbell Push Press', 'Halterofilia', 'Press de hombros con mancuernas utilizando impulso de piernas (dip and drive).', 'Mancuernas'),
('Dumbbell Push Jerk', 'Halterofilia', 'Press de hombros con mancuernas impulsado con piernas y recibiendo con flexión de rodillas bajo el peso.', 'Mancuernas'),
('Kettlebell Windmill', 'Halterofilia', 'Molino con pesa rusa, flexionando la cadera lateralmente mientras se sostiene una pesa rusa con el brazo totalmente extendido sobre la cabeza.', 'Pesa Rusa (Kettlebell)'),
('Dumbbell Overhead Carry', 'Halterofilia', 'Caminar manteniendo una o dos mancuernas completamente extendidas sobre la cabeza.', 'Mancuernas'),
('Farmers Carry', 'Halterofilia', 'Paseo del granjero cargando objetos pesados (mancuernas, kettlebells o barras de paseo) en cada mano a los costados del cuerpo.', 'Mancuernas o Pesas Rusas'),
('Walking Lunges', 'Gimnasia', 'Zancadas alternas avanzando de manera continua hacia el frente tocando el suelo suavemente con la rodilla trasera.', 'Ninguno'),
('Barbell Walking Lunge', 'Halterofilia', 'Zancadas caminando sosteniendo una barra cargada sobre los hombros (por detrás o por delante).', 'Barra'),
('Ring Dips', 'Gimnasia', 'Fondos gimnásticos en anillas suspendidas, bajando hasta que los hombros toquen las anillas y extendiendo por completo.', 'Anillas de gimnasia'),
('Bar Dips', 'Gimnasia', 'Fondos en barras paralelas descendiendo hasta romper los 90 grados en el codo y extendiendo arriba.', 'Barras Paralelas'),
('L-Sit', 'Gimnasia', 'Sostener el cuerpo con brazos extendidos (en anillas, paralelas o suelo) manteniendo las piernas extendidas horizontalmente formando una L.', 'Barras Paralelas o Anillas'),
('V-ups', 'Gimnasia', 'Abdominales en forma de V. Acostado, elevar simultáneamente el torso y las piernas extendidas para tocar las puntas de los pies.', 'Ninguno'),
('Hollow Rock', 'Gimnasia', 'Balanceo en posición de hollow (barquito) manteniendo core activo y lumbares pegadas al suelo.', 'Ninguno'),
('Toes-to-rings (T2R)', 'Gimnasia', 'Colgado de anillas, elevar las piernas hasta que ambos pies toquen simultáneamente las anillas de gimnasia.', 'Anillas de gimnasia'),
('Single Under', 'Monoestructural', 'Salto simple de comba donde la cuerda pasa una sola vez bajo los pies.', 'Comba / Cuerda'),
('Crossover Double Under', 'Monoestructural', 'Salto de comba cruzado doble. Combinación de saltos dobles cruzando los brazos alternamente en cada repetición.', 'Comba / Cuerda'),
('Assault Bike / Echo Bike', 'Monoestructural', 'Trabajo aeróbico o interválico en bicicleta estática con ventilador y palancas de brazos.', 'Assault Bike'),
('SkiErg', 'Monoestructural', 'Simulación de esquí de fondo en máquina Concept2 para acondicionamiento metabólico y fuerza de tracción.', 'SkiErg Concept2'),
('Sled Push', 'Monoestructural', 'Empujar un trineo cargado con discos en una distancia determinada para fuerza y resistencia de piernas.', 'Trineo (Sled)'),
('Sled Pull', 'Monoestructural', 'Arrastrar un trineo cargado hacia el cuerpo mediante una cuerda o arnés.', 'Trineo y Cuerda'),
('Sandbag Clean to Shoulder', 'Halterofilia', 'Cargar un saco de arena (sandbag) desde el suelo hasta apoyarlo sobre uno de los hombros.', 'Saco de Arena (Sandbag)'),
('D-Ball Clean to Shoulder', 'Halterofilia', 'Cargar una pelota pesada de goma (D-ball) desde el suelo y llevarla hasta el hombro.', 'D-Ball / Balón Pesado'),
('Dumbbell Bench Press', 'Halterofilia', 'Press de banca acostado sobre un banco plano empujando un par de mancuernas.', 'Mancuernas y Banco'),
('Man Maker', 'Halterofilia', 'Combinación de burpee sobre mancuernas, remo a una mano con cada brazo en plancha, flexión y thruster con las mancuernas al ponerse de pie.', 'Mancuernas'),
('Cluster', 'Halterofilia', 'Combinación de un Squat Clean seguido directamente de un Thruster en una sola repetición continua.', 'Barra'),
('Baby Maker', 'Gimnasia', 'Estiramiento y ejercicio de movilidad en cuclillas profundas abriendo las rodillas con los codos y sosteniendo los pies.', 'Ninguno'),
('Monster Walk', 'Gimnasia', 'Caminar lateralmente o hacia adelante con una banda de resistencia alrededor de los tobillos o rodillas manteniendo una media sentadilla.', 'Banda elástica (Band)'),
('Bear Crawl', 'Gimnasia', 'Caminar en cuatro puntos de apoyo (manos y pies) con las rodillas suspendidas cerca del suelo y la espalda recta.', 'Ninguno'),
('Crab Walk', 'Gimnasia', 'Desplazamiento cuadrupédico boca arriba apoyado sobre las manos y las plantas de los pies.', 'Ninguno'),
('Dumbbell Cluster', 'Halterofilia', 'Cargar las mancuernas desde el suelo hasta los hombros en sentadilla profunda y realizar un thruster.', 'Mancuernas'),
('Barbell Row', 'Halterofilia', 'Remo con barra inclinando el torso al frente y jalando la barra hacia el abdomen.', 'Barra'),
('Dumbbell Row', 'Halterofilia', 'Remo con mancuerna, apoyado en un banco o de pie con el torso inclinado.', 'Mancuerna (Dumbbell)'),
('Strict Press', 'Halterofilia', 'Press militar estricto de hombros empujando la barra hacia arriba desde el pecho sin impulso de piernas.', 'Barra'),
('Overhead Lunge', 'Halterofilia', 'Zancadas sosteniendo la barra, mancuerna o pesa rusa completamente extendida sobre la cabeza.', 'Barra o Mancuerna'),
('Dumbbell Lunge', 'Halterofilia', 'Zancadas sosteniendo mancuernas a los costados del cuerpo.', 'Mancuernas'),
('Kettlebell Goblet Lunge', 'Halterofilia', 'Zancadas sosteniendo una pesa rusa pegada al pecho en posición de goblet.', 'Pesa Rusa (Kettlebell)'),
('Plank (Plancha)', 'Gimnasia', 'Sostener el cuerpo en línea recta apoyado sobre los antebrazos y las puntas de los pies, activando el core.', 'Ninguno'),
('Side Plank', 'Gimnasia', 'Sostener el cuerpo lateralmente apoyado en un antebrazo y el lateral del pie.', 'Ninguno'),
('Superman Hold', 'Gimnasia', 'Acostado boca abajo, elevar pecho, brazos y piernas extendidos contrayendo la cadena posterior.', 'Ninguno'),
('Good Morning', 'Halterofilia', 'Bisagra de cadera inclinando el torso adelante con la barra sobre los hombros por detrás.', 'Barra'),
('Dumbbell Good Morning', 'Halterofilia', 'Inclinación de torso adelante sosteniendo una mancuerna o disco pegado al pecho.', 'Mancuerna (Dumbbell)'),
('Dead Bug', 'Gimnasia', 'Ejercicio de estabilidad de core coordinando la extensión de brazo y pierna contraria boca arriba.', 'Ninguno'),
('Bird Dog', 'Gimnasia', 'Ejercicio cuadrupédico extendiendo simultáneamente un brazo y la pierna opuesta manteniendo la espalda neutra.', 'Ninguno'),
('Jefferson Curl', 'Halterofilia', 'Flexión progresiva vértebra por vértebra de la columna hacia abajo sosteniendo un peso ligero desde un cajón.', 'Pesa Rusa o Mancuerna'),
('Russian Twist', 'Gimnasia', 'Giros rusos para abdomen, sentado con piernas elevadas rotando el torso de lado a lado con o sin peso.', 'Disco o Balón Medicinal'),
('Wall Sit', 'Gimnasia', 'Sostener sentadilla isométrica a 90 grados apoyando la espalda contra la pared.', 'Ninguno'),
('Glute Bridge', 'Gimnasia', 'Elevación de cadera boca arriba apoyando hombros y plantas de pies.', 'Ninguno'),
('Barbell Hip Thrust', 'Halterofilia', 'Empuje de cadera apoyando la espalda alta en un banco con una barra cargada sobre la pelvis.', 'Barra y Banco'),
('Dumbbell Hip Thrust', 'Halterofilia', 'Empuje de cadera apoyando la espalda en banco con una mancuerna sobre la pelvis.', 'Mancuerna y Banco'),
('Single-leg Glute Bridge', 'Gimnasia', 'Puente de glúteo a una sola pierna manteniendo la otra elevada.', 'Ninguno'),
('Calf Raises', 'Gimnasia', 'Elevación de talones para trabajar los gemelos de pie.', 'Ninguno'),
('Triple Under', 'Monoestructural', 'Salto triple de comba. La cuerda pasa tres veces por debajo de los pies en un solo salto.', 'Comba / Cuerda'),
('Hand Release Push-up', 'Gimnasia', 'Flexión de brazos despegando brevemente las manos del suelo al tocar con el pecho antes de empujar.', 'Ninguno'),
('Clapping Push-up', 'Gimnasia', 'Flexión pliométrica empujando con fuerza para dar un aplauso en el aire antes de recibir el cuerpo.', 'Ninguno'),
('Deficit Push-up', 'Gimnasia', 'Flexión con manos elevadas sobre discos o paralelas para lograr mayor profundidad y rango.', 'Discos o Paralelas'),
('Strict Ring Dip', 'Gimnasia', 'Fondos en anillas realizados estrictamente con fuerza de tríceps y pectoral, sin balanceo.', 'Anillas de gimnasia'),
('Kipping Ring Dip', 'Gimnasia', 'Fondos en anillas utilizando flexión e impulso de cadera y rodillas (kipping) para subir.', 'Anillas de gimnasia'),
('Kipping Handstand Push-up', 'Gimnasia', 'Flexiones de pino contra la pared utilizando el impulso de las piernas y la cadera.', 'Pares / Abmat'),
('Dragon Flag', 'Gimnasia', 'Ejercicio abdominal avanzado elevando el cuerpo en una sola línea apoyado solo en hombros y cuello agarrando un soporte.', 'Soporte Fijo'),
('Toes-to-Bar (Strict)', 'Gimnasia', 'Llevar los pies a la barra colgado de forma estrictamente de fuerza sin balanceo.', 'Barra de dominadas'),
('Chin-up', 'Gimnasia', 'Dominadas con agarre supino (palmas hacia la cara), enfocando el esfuerzo en bíceps y dorsales.', 'Barra de dominadas'),
('Chest-to-Bar Chin-up', 'Gimnasia', 'Dominadas supinas llevando el pecho a tocar la barra fija.', 'Barra de dominadas'),
('Tuck Jump', 'Gimnasia', 'Salto vertical llevando las rodillas lo más alto posible hacia el pecho en el aire.', 'Ninguno'),
('Broad Jump', 'Monoestructural', 'Salto largo desde parado buscando cubrir la máxima distancia horizontal.', 'Ninguno'),
('Banded Face Pull', 'Gimnasia', 'Jalón hacia la cara con banda elástica para trabajar deltoides posterior y rotadores.', 'Banda elástica (Band)'),
('Banded Pull Apart', 'Gimnasia', 'Abrir los brazos extendidos estirando una banda elástica frente al pecho.', 'Banda elástica (Band)')
ON CONFLICT (nombre) DO NOTHING;
